### PR TITLE
Added Monterey, Ventura and Sonoma icons

### PR DESCRIPTION
**Pull request by perez987**
Good morning, congratulations for your work, I like it but, although it works very well, I miss the Monterey, Ventura and Sonoma icons in the macOS packages list. 
I've added them and updated the screenshot. I have also updated defaultCatalog.swift file to include recent macOS versions.

DownloadFullInstaller-1 2-screenshot

### CODE REVIEW

**Comment by MysticalOS** [comment]
Kinda sad to see this PR sit for so long. I only hope it's eventually merged

**Comment by perez987** [comment]
@MysticalOS 
No worries, I like the app but it was a little outdated.

**Comment by huyz** [comment]
Merge, merge

**Comment by perez987** [comment]
Great!!! Thanks.

**Pull request closed without merging**
